// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SNAKE_H_
#define FLATBUFFERS_GENERATED_SNAKE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

struct Pos;

struct SnakeObj;
struct SnakeObjBuilder;

struct GameData;
struct GameDataBuilder;

enum State : int8_t {
  State_Alive = 0,
  State_Idle = 1,
  State_Dead = 2,
  State_MIN = State_Alive,
  State_MAX = State_Dead
};

inline const State (&EnumValuesState())[3] {
  static const State values[] = {
    State_Alive,
    State_Idle,
    State_Dead
  };
  return values;
}

inline const char * const *EnumNamesState() {
  static const char * const names[4] = {
    "Alive",
    "Idle",
    "Dead",
    nullptr
  };
  return names;
}

inline const char *EnumNameState(State e) {
  if (::flatbuffers::IsOutRange(e, State_Alive, State_Dead)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesState()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Pos FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;

 public:
  Pos()
      : x_(0),
        y_(0) {
  }
  Pos(int32_t _x, int32_t _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  int32_t x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Pos, 8);

struct SnakeObj FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SnakeObjBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_STATE = 6,
    VT_BODY = 8
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  State state() const {
    return static_cast<State>(GetField<int8_t>(VT_STATE, 0));
  }
  const ::flatbuffers::Vector<const Pos *> *body() const {
    return GetPointer<const ::flatbuffers::Vector<const Pos *> *>(VT_BODY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_STATE, 1) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyVector(body()) &&
           verifier.EndTable();
  }
};

struct SnakeObjBuilder {
  typedef SnakeObj Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(SnakeObj::VT_ID, id, 0);
  }
  void add_state(State state) {
    fbb_.AddElement<int8_t>(SnakeObj::VT_STATE, static_cast<int8_t>(state), 0);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::Vector<const Pos *>> body) {
    fbb_.AddOffset(SnakeObj::VT_BODY, body);
  }
  explicit SnakeObjBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SnakeObj> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SnakeObj>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SnakeObj> CreateSnakeObj(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    State state = State_Alive,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Pos *>> body = 0) {
  SnakeObjBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_id(id);
  builder_.add_state(state);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SnakeObj> CreateSnakeObjDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    State state = State_Alive,
    const std::vector<Pos> *body = nullptr) {
  auto body__ = body ? _fbb.CreateVectorOfStructs<Pos>(*body) : 0;
  return CreateSnakeObj(
      _fbb,
      id,
      state,
      body__);
}

struct GameData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SNAKES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<SnakeObj>> *snakes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<SnakeObj>> *>(VT_SNAKES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SNAKES) &&
           verifier.VerifyVector(snakes()) &&
           verifier.VerifyVectorOfTables(snakes()) &&
           verifier.EndTable();
  }
};

struct GameDataBuilder {
  typedef GameData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_snakes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SnakeObj>>> snakes) {
    fbb_.AddOffset(GameData::VT_SNAKES, snakes);
  }
  explicit GameDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameData> CreateGameData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<SnakeObj>>> snakes = 0) {
  GameDataBuilder builder_(_fbb);
  builder_.add_snakes(snakes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GameData> CreateGameDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<SnakeObj>> *snakes = nullptr) {
  auto snakes__ = snakes ? _fbb.CreateVector<::flatbuffers::Offset<SnakeObj>>(*snakes) : 0;
  return CreateGameData(
      _fbb,
      snakes__);
}

inline const GameData *GetGameData(const void *buf) {
  return ::flatbuffers::GetRoot<GameData>(buf);
}

inline const GameData *GetSizePrefixedGameData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GameData>(buf);
}

template <bool B = false>
inline bool VerifyGameDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<GameData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedGameDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<GameData>(nullptr);
}

inline void FinishGameDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GameData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGameDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GameData> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_SNAKE_H_
